redhataccess/redhat_access_pcm_ascension_common

- bower.json
- dist/redhat_access_pcm_ascension_common.js
- package.json
> Bumping version

- app/common/directives/choice.js
- app/common/directives/choicetree.js
- app/common/directives/enter.js
- app/common/directives/optionsDisabled.js
- app/common/directives/resizable.js
- app/common/factories/treeViewSelectorData.js
- app/common/factories/treeViewSelectorUtils.js
- app/common/filters/trust.js
- app/common/services/translate.js
- app/common/ui-utils.module.js
- bower.json
- dist/redhat_access_pcm_ascension_common.js
- package.json
Modularizing the rest of the ui-utils module so we can pull in more individual things into Ascension like rhaEnter.
> PCM-:2907 Modularizing the rest of ui-utils

- app/common/services/udsService.js
- bower.json
- dist/redhat_access_pcm_ascension_common.js
- package.json
@engineersamuel @vrathee Please review
> pcm-2757 code changes

- app/common/services/udsService.js
- bower.json
- dist/redhat_access_pcm_ascension_common.js
- package.json
Adding UQL endpoints for SQI and CQI based on the https://github.com/redhataccess/udsjs/pull/74 (which must first be merged and pushed to bower/npm)
> PCM-2960: Adding UQL endpoints for SQI and CQI

- bower.json
- dist/redhat_access_pcm_ascension_common.js
- package.json
> Fix for PCM-2989

- app/common/services/udsService.js
- bower.json
- dist/redhat_access_pcm_ascension_common.js
- package.json
> PCM-2923: Added case owner update

- app/common/services/udsService.js
- bower.json
- dist/redhat_access_pcm_ascension_common.js
- package.json
@gandhikeyur @jtrantin Please Review.
> Getting CallCenter Details for Genesys Integration

- app/common/services/udsService.js
- dist/redhat_access_pcm_ascension_common.js
- package.json
@jtrantin @gandhikeyur Please Review
> Api's for case tags

- app/common/controllers/titleView.js
- bower.json
- dist/redhat_access_pcm_ascension_common.js
- package.json
Was function, fixed to constructor.  Built and verified fix in pcm.
> PCM-3049: Fix ES6 class def for titleView.js

- app/common/services/udsService.js
- bower.json
- dist/redhat_access_pcm_ascension_common.js
- package.json
@renujhamtani @gandhikeyur Please review
> Changes for making public comment private

- app/common/services/udsService.js
- bower.json
- dist/redhat_access_pcm_ascension_common.js
- package.json
https://projects.engineering.redhat.com/browse/PCM-3090
> PCM-3090: Adding user-role update API

- app/common/services/udsService.js
- bower.json
- dist/redhat_access_pcm_ascension_common.js
- package.json
https://projects.engineering.redhat.com/browse/PCM-2875
> PCM-2875: Added case languages API

- app/common/services/rhaUtils.js
- bower.json
- dist/redhat_access_pcm_ascension_common.js
- package.json
@jtrantin @vrathee Please review
> Pcm 3117 timeZone related changes to isWeeekEnd function

- app/common/services/udsService.js
- bower.json
- dist/redhat_access_pcm_ascension_common.js
- package.json
@vrathee @gandhikeyur @engineersamuel Please review.
https://projects.engineering.redhat.com/browse/PCM-3133
Related uds.js PR: https://github.com/redhataccess/udsjs/pull/85
> PCM-3133: Added new User APIs

- app/common/services/strataService.js
- bower.json
- dist/redhat_access_pcm_ascension_common.js
- package.json
> PCM-3133: Added getUserBySSO API from strata.js

- app/common/services/strataService.js
- bower.json
- package.json
This forgotten typo can cause problems if there is an error during the request.
> Fixed wrong error handler binding

- README.md
- app/common/services/strataService.js
- bower.json
- dist/redhat_access_pcm_ascension_common.js
- package.json
https://projects.engineering.redhat.com/browse/PCM-3317
Also removing ie8 references.
> PCM-3317: caching cases:search and cases:advancedSearch

- README.md
- app/common/services/strataService.js
- bower.json
- dist/redhat_access_pcm_ascension_common.js
- package.json
https://projects.engineering.redhat.com/browse/PCM-3317
Also removing ie8 references.
> Revert "PCM-3317: caching cases:search and cases:advancedSearch"

- app/common/services/udsService.js
- bower.json
- dist/redhat_access_pcm_ascension_common.js
- package.json
https://projects.engineering.redhat.com/browse/PCM-3154
Splitting the solr api in udsService to Access and Cases APIs. Will submit the ascension changes shortly.
> PCM-3154: Split SOLR in udsService to Access and Case collection

- app/common/services/udsService.js
- bower.json
- dist/redhat_access_pcm_ascension_common.js
- package.json
@gandhikeyur @engineersamuel Please review
> PCM-3369 Fix edit genesys details

- app/common/services/strataService.js
- bower.json
- dist/redhat_access_pcm_ascension_common.js
- package.json
> PCM-3048: Passing case format in cases.advancedSearch

- app/common/services/constantsService.js
- bower.json
- dist/redhat_access_pcm_ascension_common.js
- package.json
Added the available columns as a constant.
> PCM-3047: Added constants for Advanced Search case list

- app/common/services/udsService.js
- bower.json
- dist/redhat_access_pcm_ascension_common.js
- package.json
@jtrantin @vrathee Please review
> pcm-3281 setGbdSuperRegion code changes

- app/common/services/udsService.js
- bower.json
- dist/redhat_access_pcm_ascension_common.js
- package.json
@vrathee @jtrantin Please review
https://projects.engineering.redhat.com/browse/PCM-3295
Related UDS Jira: https://projects.engineering.redhat.com/browse/UNIFIED-1488
> pcm-3295 nep related changes to fetch top cases query

- app/common/services/strataService.js
- bower.json
- dist/redhat_access_pcm_ascension_common.js
- package.json
> PCM-3162: Passing progress callback to strata.js

- app/common/services/udsService.js
- bower.json
- dist/redhat_access_pcm_ascension_common.js
- package.json
@vrathee @jtrantin Please review
> pcm-3580 function to add OOO to a user

- app/security/services/securityService.js
- bower.json
- dist/redhat_access_pcm_ascension_common.js
- package.json
> PCM-3721: Fixing liveagent initialization

- app/security/services/securityService.js
- bower.json
- dist/redhat_access_pcm_ascension_common.js
- package.json
Randomly stumbled on this issue, so I'm submitting a fix before I forget about it.
@gandhikeyur @engineersamuel Please review.
> Forgotten promise resolution in authentication + PCM-3818

- app/common/services/udsService.js
- bower.json
- dist/redhat_access_pcm_ascension_common.js
- package.json
@vrathee @gandhikeyur Please review. Adding function for updateResourceLink in uds.js, as in https://github.com/redhataccess/udsjs/pull/93.
> PCM-3391: Added updateResourceLink call-through function

- app/common/services/strataService.js
- bower.json
- dist/redhat_access_pcm_ascension_common.js
- package.json
@vrathee @gandhikeyur @engineersamuel Please review.
https://projects.engineering.redhat.com/browse/PCM-4142
The problem here was the entitlements response was too big and the store in strataCache failed. That caused the promise never being resolved and that lead to the problems in PCM-4142. I just removed a caching for that request.
> PCM-4142: Removing cache from entitlements request

- app/common/services/strataService.js
- app/common/services/udsService.js
- bower.json
- dist/redhat_access_pcm_ascension_common.js
- package.json
@renujhamtani @jtrantin Please review
https://projects.engineering.redhat.com/browse/PCM-3174
> Pcm 3174 - Adding API's for adding and updating private attachments

- app/security/services/securityService.js
- bower.json
- package.json
@renujhamtani @jtrantin Please review and tag
The problem was we were null checking `this.loginStatus.authedUser.account` before setting it.. moved this call after setting account details and it worked.
> Fix for BZ-1418926

- app/common/services/strataService.js
- app/security/services/securityService.js
- bower.json
- package.json
@jtrantin @renujhamtani Please Review
https://projects.engineering.redhat.com/browse/PCM-4334
> API changes for PCM-4334

- app/common/services/strataService.js
- bower.json
- dist/redhat_access_pcm_ascension_common.js
- package.json
@gandhikeyur @renujhamtani Please review.
> PCM-4485: Clearing all case search caches on case update

- app/common/services/strataService.js
- bower.json
- dist/redhat_access_pcm_ascension_common.js
- package.json
@gandhikeyur Review. I am going to merge this as it's a simple change.
> +PCM-4485: Adding cache clean to comments APIs

- app/security/services/securityService.js
- bower.json
- dist/redhat_access_pcm_ascension_common.js
- package.json
@vrathee @kunyan Please review
> Pcm 4511 - Fetching logged in user contact details while logging in

- app/security/services/securityService.js
- bower.json
- dist/redhat_access_pcm_ascension_common.js
- package.json
@vrathee @renujhamtani Please review.
https://projects.engineering.redhat.com/browse/PCM-4460
https://projects.engineering.redhat.com/browse/PCM-4260
> PCM-4460 & PCM-4260 : secure support portal changes

- app/common/services/strataService.js
- bower.json
- dist/redhat_access_pcm_ascension_common.js
- package.json
@vrathee @engineersamuel @kunyan Please review
> pcm-4460 code changes

- app/common/services/constantsService.js
- bower.json
- dist/redhat_access_pcm_ascension_common.js
- package.json
@vrathee @engineersamuel Please review.
https://projects.engineering.redhat.com/browse/PCM-4137
> pcm-4137 code changes

- app/common/services/strataService.js
- bower.json
- dist/redhat_access_pcm_ascension_common.js
- package.json
@engineersamuel @vrathee @anujsi @kunyan @renujhamtani Please review.
https://projects.engineering.redhat.com/browse/PCM-5350
> pcm-5350 solution engine related code changes

- app/common/views/403.jade
- app/security/services/securityService.js
- bower.json
- dist/redhat_access_pcm_ascension_common.js
- package.json
@engineersamuel @anujsi @renujhamtani Please review.
https://projects.engineering.redhat.com/browse/PCM-5665
> pcm-5665 : resolving infinte loop changes on invalid subscription error

- app/common/services/strataService.js
- bower.json
- dist/redhat_access_pcm_ascension_common.js
- package.json
@gandhikeyur @engineersamuel Please review.
https://projects.engineering.redhat.com/browse/PCM-5905
> pcm-5905 : case list does not show next page .

- app/common/services/strataService.js
- bower.json
- dist/redhat_access_pcm_ascension_common.js
- package.json
@engineersamuel @kunyan @gandhikeyur @asonawan Please review.
> PCM-5730 - Partner query should search client account(s) .

- app/common_shared/hydrajs.js
- package.json
missed in the last code submit.
> add hydrajs file .

- app/common/services/strataService.js
- dist/redhat_access_pcm_ascension_common.js
- package.json
@anujsi @gandhikeyur Please review
> PCM-7155 Updated to use jquery v3

- app/common/services/strataService.js
- dist/redhat_access_pcm_ascension_common.js
@gandhikeyur @vrathee @aksgupta14 @asonawan Please review.
https://projects.engineering.redhat.com/browse/PCM-7265
> PCM-7265 - sorting comments in PCM by published_date .

- app/security/services/securityService.js
- dist/redhat_access_pcm_ascension_common.js
> PCM-7317 added CEP flag.

- app/common/services/strataService.js
- bower.json
- dist/redhat_access_pcm_ascension_common.js
- package.json
stratajs changes : `https://github.com/redhataccess/stratajs/pull/61/files?w=1`
Please review @anujsi @vrathee @ascension
> PCM-7771: updates signature as per stratajs changes

- app/common/controllers/header.js
> Share Case with Partner: Don't reset alerts when only QP has changed.

- bower.json
- package.json
Reverts redhataccess/redhat_access_pcm_ascension_common#74
> Revert "Publish version 1.2.77"

- app/common/services/strataService.js
> PCM-8117: added new variables for starta advanced search

- .gitignore
- app/common/services/strataService.js
@jeudy100 @vrathee Please review.
https://projects.engineering.redhat.com/browse/PCM-8469
> PCM-8469 - Advanced case search not returning expected results .

- app/common/services/alertService.js
@vrathee @anujsi please review
> handle 500 errors gracefully

- app/common/services/strataService.js
@rh-kgarg @vrathee @aksgupta14 Please review.
https://projects.engineering.redhat.com/browse/PCM-6822
> PCM-6822 - added contenttype field in the comment .
